language: bash
services: docker

before_install:
  # Wait 50 minutes to avoid travis timeout.
  # https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
  - travis_wait 50 docker build -t ionic-android .

script:
  - docker run ionic-android /bin/sh -c "ionic -v && ionic config set -g backend legacy && ionic start test blank --no-link --no-git --cordova && cd test && ionic cordova platform add android --no-resources && ionic cordova build android"

after_script:
  - docker images

